spring.datasource.url=jdbc:postgresql://localhost:5432/mindflow_db
spring.datasource.username=mindflow_user
spring.datasource.password=mindflow_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações do Jackson (JSON serialization)
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=UTC

# Configurações do RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest