spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mindflow_db
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    filter:
      dispatcher-types: request, async, error

jwt:
  secret: bee782a65b499088971509f1685d8de08ed59e017d19acc69136a2fee56a2766
  expiration: 86400000        

server:
  port: 8080
  servlet:
    context-path: /api
    
logging:
  level:
    org.springframework.security: DEBUG